# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Wreath' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Wreath

  # 请求工具
pod 'Moya', '~> 11.0'
#pod 'Moya/RxSwift', '~> 11.0'
# json转model
pod 'HandyJSON'
# 图片加载
pod 'Kingfisher'
# swift的Masonry
pod 'SnapKit'
#pod 'R.swift'

end
